### PR TITLE
fixed powerupBomb score and vfx problem

### PR DESCRIPTION
**Pull request by newspeak1984**

### CODE REVIEW

**Review by ktorii — COMMENTED** [review]
Does this work for the laser too? The points should be 10, 20, 30 for small medium big balls.

**Comment by newspeak1984** [comment]
What do you mean by does this work for laser? And I just added to the score based on the set variables. Ex. Smallballvalue

**Comment by ktorii** [comment]
does the score go up properly for the laser powerup too.
the code is weird for scores right now because we have a line like this:
ball2.LargeScoreValue = MedScoreValue;

Just double check to make sure the proper values to the score are working. then i'll merge this.

**Comment by newspeak1984** [comment]
Ok, I'll check both those things when I get back.

**Pull request merged**
